In [1]:
import numpy as np

In [14]:
a = [1,2,3,4]
b = [5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
[a[i] + b[i] for i in range(len(a)]

[6, 8, 10, 12]

In [16]:
#using np arrays
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr[1:,:] 

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [36]:
np.eye(3,3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[a%2==0]

array([2, 4])

In [47]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [96]:
np.linspace(1,2,8).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 2])

In [59]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [60]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [64]:
a+b 

array([[ 6,  8],
       [10, 12]])

In [65]:
a*b

array([[ 5, 12],
       [21, 32]])

In [70]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
np.linalg.inv(arr)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [76]:
np.linalg.det(arr)

np.float64(-9.51619735392994e-16)

In [77]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [78]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.reshape(arr,(1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [88]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [145]:
np.reshape(a,(3,4))

array([[ 1,  2,  8,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
np.resize(a,(3,2))

array([[1, 2],
       [8, 4],
       [5, 6]])

In [95]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [97]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [147]:
b = a.view()
b[3]= 0
a,b

(array([ 1,  2,  8,  0,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 1,  2,  8,  0,  5,  6,  7,  8,  9, 10, 11, 12]))

In [106]:
c=a.copy()
a,c

(array([ 1,  2,  8,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 1,  2,  8,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [109]:
c[2] = 6
a,c

(array([ 1,  2,  8,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 1,  2,  6,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [111]:
ar1 = np.array([1,2,3,4,5])
ar1

array([1, 2, 3, 4, 5])

In [112]:
np.mean(ar1)

np.float64(3.0)

In [118]:
#mean function
def mean(array):
    n=len(array)
    return np.sum(array)/n
mean(ar1)

np.float64(3.0)

In [124]:
#variance function:
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array -m )**2)/n
variance(ar1)

np.float64(2.0)

In [127]:
#min-max scalar
def minmax(array):
    min = np.min(array)
    max = np.max(array)
    return ((array) - min) / (max - min)
minmax(ar1)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [128]:
#standard scalar:
def std_sc(array):
    m = mean(array)
    s = variance(array)
    return (array - m) / s
std_sc(ar1)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [140]:
#sigmoid:
def sigmoid(array):
    exp = np.exp(-array)
    return 1 / 1 + exp
sigmoid(ar1)

array([1.36787944, 1.13533528, 1.04978707, 1.01831564, 1.00673795])

In [142]:
#relu:
def relu(array):
    return np.maximum(0,array)  
relu(ar1)

array([1, 2, 3, 4, 5])

In [150]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])